---
- name: detect latest awless release
  github_release:
    repository: wallix/awless
    release: "{{ devhost_awless_release }}"
    creates: "{{ devhost_awless_binary }}"
    reinstall: "{{ devhost_upgrade |bool }}"
    template: '{download_url}/awless-linux-amd64.tar.gz'
  tags: skip_ansible_lint
  register: latest_awless_release

- name: download awless
  unarchive:
    remote_src: true
    src: "{{ latest_awless_release.url }}"
    dest: "{{ devhost_awless_binary |dirname }}"
  when: latest_awless_release is changed

- name: bash completion for awless
  shell: awless completion bash > /etc/bash_completion.d/awless
  when: latest_awless_release is changed
...
