---
- name: add azure signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
  # fix sporadic .ru network failures
  register: apt_key_result
  until: "'timed out' not in apt_key_result.msg |default('')"

- name: add azure repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_lsb.codename }} main"
    filename: azure-cli

- name: install azure cli
  apt:
    name: azure-cli
    state: "{{ devhost_upgrade |bool |ternary('latest','present') }}"
...
