---
- name: detect latest do-ctl release
  github_release:
    repository: digitalocean/doctl
    release: "{{ devhost_doctl_release }}"
    creates: "{{ devhost_doctl_binary }}"
    reinstall: "{{ devhost_allow_reinstall |bool }}"
    strip_v: true
    template: "{download_url}/doctl-{ver}-linux-amd64.tar.gz"
  register: latest_doctl_release

- name: download do-ctl
  unarchive:
    remote_src: true
    src: "{{ latest_doctl_release.url }}"
    dest: "{{ devhost_doctl_binary |dirname }}"
  when: latest_doctl_release is changed

- name: bash completion for do-ctl
  lineinfile:
    path: ~/.local/bashrc/5completion.sh
    line: "source <(doctl completion bash)"
  become: false

- name: authenticate with digital ocean
  # use transient environment variable to hide token from command line
  shell: >
    {{ devhost_doctl_binary }} auth init -t "$_digitalocean_token"
  args:
    creates: ~/.config/doctl/config.yaml
  environment:
    _digitalocean_token: "{{ devhost_digitalocean_token }}"
  become: false
  when: devhost_digitalocean_token != ''
...
