---
- name: detect latest do-ctl release
  uri:
    url: https://github.com/digitalocean/doctl/releases/latest
    method: HEAD
    creates: "{{ linhost_allow_reinstall | ternary(omit, linhost_doctl_binary) }}"
  #connection: local  # never use this with "creates"
  register: latest_doctl_release
  when: linhost_doctl_release == 'latest'

- set_fact:
    linhost_doctl_release:
      "{{ latest_doctl_release.url | basename | regex_replace('^v') }}"
  when: latest_doctl_release is not skipped
        and latest_doctl_release.url is defined

- debug:
    msg: "latest do-ctl release: {{ linhost_doctl_release }}"
  run_once: true
  when: latest_doctl_release is not skipped
        and latest_doctl_release.url is defined

- name: download do-ctl
  unarchive:
    remote_src: yes
    src: https://github.com/digitalocean/doctl/releases/download/v{{ linhost_doctl_release }}/doctl-{{ linhost_doctl_release }}-linux-amd64.tar.gz
    dest: "{{ linhost_doctl_binary | dirname }}"
    creates: "{{ linhost_allow_reinstall | ternary(omit, linhost_doctl_binary) }}"

- name: authenticate with digital ocean
  # use transient environment variable to hide token from command line
  shell: >
    {{ linhost_doctl_binary }} auth init -t "$_doctl_token"
  args:
    creates: ~/.config/doctl/config.yaml
  environment:
    _doctl_token: "{{ linhost_doctl_token }}"
  become: no
  when: linhost_doctl_token != ''
...
