---
# tasks file for ivansible.lin_hosters

- setup:

- import_tasks: aws.yml
  become: yes
  tags: linhost_aws

- import_tasks: azure.yml
  become: yes
  tags: linhost_azure

- import_tasks: do.yml
  become: yes
  tags: linhost_do

- import_tasks: heroku.yml
  become: yes
  tags: linhost_heroku

- import_tasks: vultr.yml
  become: yes
  tags: linhost_vultr
...
