---
- name: verify that user-local bash completions exist
  stat:
    path: "{{ _devhost_user_bash_completions }}"
  register: _stat_user_bash_completions
  become: false
  tags:
    - devhost_all
    - dev_hosters_all

- name: become root and install hoster tools
  import_tasks: root.yml
  become: true
  tags:
    - devhost_all
    - dev_hosters_all
...
