---
# tasks file for ivansible.lin_hosters

- setup:

- block:
    - import_tasks: aws.yml
      tags: linhost_aws

    - import_tasks: azure.yml
      tags: linhost_azure

    - import_tasks: do.yml
      tags: linhost_do

    - import_tasks: heroku.yml
      tags: linhost_heroku

    - import_tasks: vultr.yml
      tags: linhost_vultr
  become: yes
  tags: lin_hosters
  # end of block

- import_tasks: terraform.yml
  become: no
  tags:
  - linhost_terraform
  - lin_hosters
  - ip4only
...
