---
# tasks for ivansible.dev_hosters
- block:
    - import_tasks: aws.yml
      tags: devhost_aws

    - import_tasks: azure.yml
      tags: devhost_azure

    - import_tasks: digitalocean.yml
      tags: devhost_digitalocean

    - import_tasks: heroku.yml
      tags: devhost_heroku

    - import_tasks: vultr.yml
      tags: devhost_vultr
  become: true
  tags: dev_hosters
  # end of block
...
