---
- name: check that Packet cli binary already exists
  stat:
    path: "{{ devhost_packet_binary }}"
  register: packet_binary

- block:
    - name: detect installed Go version
      set_fact:
        devhost_packet_golang_version: "{{ devhost_packet_golang_version
                                         | default(linbase_golang_version, true)
                                         | default(dev_user_golang_version, true)
                                         | default('0', true) }}"

    - name: install Go 1.10 for building Packet cli
      apt:
        name: golang-1.10
      when: devhost_packet_golang_version is version('1.10', '<')

    - name: set Go version for building Packet cli
      set_fact:
        devhost_packet_golang_version: '1.10'
      when: devhost_packet_golang_version is version('1.10', '<')

    - name: create temporary directory for building Packet cli
      tempfile:
        prefix: build-packet-cli.
        state: directory
      register: packet_build_dir
      notify: remove packet-cli build directory

    - name: build Packet cli from source
      go:
        name: github.com/ebsarr/packet
        go_path: "{{ packet_build_dir.path }}"
      environment:
        GOROOT: "{{ go_root }}"
        PATH: "{{ go_root }}/bin:/usr/bin:/bin:/usr/local/bin"
      vars:
        go_root: /usr/lib/go-{{ devhost_packet_golang_version }}

    - name: copy Packet cli in place
      synchronize:
        src: "{{ packet_build_dir.path }}/bin/packet"
        dest: "{{ devhost_packet_binary }}"
      delegate_to: "{{ inventory_hostname }}"
      notify: remove packet-cli build cache

  when: devhost_allow_reinstall |bool
        or not packet_binary.stat.exists

- name: cleanup temporary Packet files
  meta: flush_handlers

- block:
    - name: create directory for Packet cli profile
      file:
        path: "{{ ansible_user_dir }}/.packet"
        state: directory

    - name: create Packet cli profile
      template:
        src: packet-config.json.j2
        dest: "{{ ansible_user_dir }}/.packet/config"
        mode: 0640
  when: devhost_packet_auth_token
        and devhost_packet_default_project
        and is_permitted |bool
  become: no
...
