---
- name: check that Packet cli binary already exists
  stat:
    path: "{{ devhost_packet_binary }}"
  register: packet_binary

- block:
    - name: install golang for building Packet cli
      import_role:
        name: ivansible.lin_go
        # exports lin_go_version

    - name: create temporary directory for building Packet cli
      tempfile:
        prefix: build-packet-cli.
        state: directory
      register: packet_build_dir
      notify: remove packet-cli build directory

    - name: build Packet cli from source
      go:
        name: github.com/ebsarr/packet
        go_path: "{{ packet_build_dir.path }}"
      tags: skip_ansible_lint
      environment:
        GOROOT: "{{ go_root }}"
        PATH: "{{ go_root }}/bin:/usr/bin:/bin:/usr/local/bin"
      vars:
        go_root: /usr/lib/go-{{ lin_go_version }}
      register: _build_packet_cli
      until: _build_packet_cli is successful

    - name: copy Packet cli in place
      synchronize:
        src: "{{ packet_build_dir.path }}/bin/packet"
        dest: "{{ devhost_packet_binary }}"
      delegate_to: "{{ inventory_hostname }}"
      notify: remove packet-cli build cache

  when: devhost_upgrade |bool
        or not packet_binary.stat.exists

- name: cleanup temporary Packet files
  meta: flush_handlers

- block:
    - name: create directory for Packet cli profile
      file:
        path: "{{ ansible_user_dir }}/.packet"
        state: directory
        mode: 0755

    - name: create Packet cli profile
      template:
        src: packet-config.json.j2
        dest: "{{ ansible_user_dir }}/.packet/config"
        mode: 0640
  when:
    - devhost_packet_auth_token |d('')
    - devhost_packet_default_project |d('')
    - is_permitted |bool
  become: false
...
