---
- import_tasks: aws.yml
  tags: devhost_aws
  when: devhost_aws_enabled |bool

- import_tasks: awless.yml
  tags: devhost_awless

- import_tasks: azure.yml
  tags: devhost_azure
  when: devhost_azure_enabled |bool

- import_tasks: digitalocean.yml
  tags:
    - devhost_digitalocean
    - devhost_do

- import_tasks: heroku.yml
  tags: devhost_heroku
  when: devhost_heroku_enabled |bool

- import_tasks: packet.yml
  tags: devhost_packet
  when: devhost_packet_enabled |bool

- import_tasks: vultr.yml
  tags: devhost_vultr

- import_tasks: hetzner.yml
  tags: devhost_hetzner

- import_tasks: solusvm.yml
  tags: devhost_solusvm
  when: devhost_solusvm_enabled |bool
...
