---
- import_tasks: aws.yml
  tags: devhost_aws
  when: devhost_aws_enabled |bool

- import_tasks: awless.yml
  tags: devhost_awless
  ## awless does not provide arm64 binaries yet
  when:
    - ansible_architecture == 'x86_64'

- import_tasks: azure.yml
  tags: devhost_azure
  when:
    - devhost_azure_enabled |bool
    ## azure-cli is not available for bionic/arm64
    - ansible_architecture == 'x86_64' or ansible_lsb.release is version('20.04','>=')

- import_tasks: digitalocean.yml
  tags:
    - devhost_digitalocean
    - devhost_do

- import_tasks: heroku.yml
  tags: devhost_heroku
  when:
    - devhost_heroku_enabled |bool
    ## TODO install heroku tarball on arm64
    ## SEE  https://devcenter.heroku.com/articles/heroku-cli#tarballs
    - ansible_architecture == 'x86_64'

- import_tasks: packet.yml
  tags: devhost_packet
  when: devhost_packet_enabled |bool

- import_tasks: vultr.yml
  tags: devhost_vultr

- import_tasks: hetzner.yml
  tags: devhost_hetzner

- import_tasks: solusvm.yml
  tags: devhost_solusvm
  when: devhost_solusvm_enabled |bool
...
