---
- name: detect latest vultr cli release
  uri:
    url: https://github.com/JamesClonk/vultr/releases/latest
    method: HEAD
    creates: "{{ devhost_allow_reinstall | ternary(omit, devhost_vultr_binary) }}"
  #connection: local  # never use this with "creates"
  register: latest_vultr_release
  when: devhost_vultr_release == 'latest'

- set_fact:
    devhost_vultr_release: "{{ latest_vultr_release.url | basename }}"
  when: latest_vultr_release is not skipped
        and latest_vultr_release.url is defined

- debug:
    msg: "latest vultr cli release: {{ devhost_vultr_release }}"
  run_once: true
  when: latest_vultr_release is not skipped
        and latest_vultr_release.url is defined

- name: download and unpack vultr cli
  unarchive:
    remote_src: yes
    src: https://github.com/JamesClonk/vultr/releases/download/{{ devhost_vultr_release }}/vultr_{{ devhost_vultr_release | regex_replace('^v') }}_Linux-64bit.tar.gz
    dest: "{{ devhost_vultr_binary | dirname }}"
    exclude:
      - LICENSE
      - README.md
    creates: "{{ devhost_allow_reinstall | ternary(omit, devhost_vultr_binary) }}"
...
