---
- name: detect latest vultr cli release
  github_release:
    repository: vultr/vultr-cli
    release: "{{ devhost_vultr_release }}"
    creates: "{{ devhost_vultr_binary }}"
    reinstall: "{{ devhost_allow_reinstall |bool }}"
    strip_v: true
    template: '{download_url}/vultr-cli_{ver}_linux_64-bit.tar.gz'
  tags: skip_ansible_lint
  register: latest_vultr_release

- name: download and unpack vultr cli
  unarchive:
    remote_src: true
    src: "{{ latest_vultr_release.url }}"
    dest: "{{ devhost_vultr_binary |dirname }}"
    exclude:
      - LICENSE
      - README.md
  when: latest_vultr_release is changed
...
