---
is_permitted: false
lin_use_ssh: false
lin_firewall: none
allow_sysctl: false
lin_core_time_sync: false
lin_core_system_locale: en_US.UTF-8

lindev_golang_version: '1.14'

# skip github cli task since module github_release needs custom collection
git_hub_release: ""
...
